# Generated by Django 3.2.12 on 2022-04-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20220325_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredfood',
            old_name='user',
            new_name='user_profile',
        ),
    ]
