# Generated by Django 3.2.12 on 2022-04-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_rename_user_registeredfood_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredfood',
            options={'verbose_name': 'Registered Food', 'verbose_name_plural': 'Registered Foods'},
        ),
        migrations.AddConstraint(
            model_name='registeredfood',
            constraint=models.UniqueConstraint(fields=('user_profile', 'food', 'meal'), name='unique_user_food_meal'),
        ),
    ]
