# Generated by Django 3.2.12 on 2022-04-14 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20220408_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('grams', models.IntegerField(help_text='Kg/Ml')),
                ('meal', models.CharField(choices=[('BKFT', 'Breakfast'), ('LNCH', 'Lunch'), ('DNNR', 'Dinner'), ('DSST', 'Dessert'), ('SNCK', 'Snack')], max_length=4)),
            ],
            options={
                'verbose_name': 'Food Consumed',
                'verbose_name_plural': 'Foods Consumed',
            },
        ),
        migrations.DeleteModel(
            name='BreakfastRegistered',
        ),
        migrations.DeleteModel(
            name='DessertRegistered',
        ),
        migrations.DeleteModel(
            name='DinnerRegistered',
        ),
        migrations.DeleteModel(
            name='LunchRegistered',
        ),
        migrations.DeleteModel(
            name='SnacksRegisteredFood',
        ),
        migrations.RemoveConstraint(
            model_name='registeredfood',
            name='unique_user_food_meal',
        ),
        migrations.RemoveField(
            model_name='registeredfood',
            name='meal',
        ),
        migrations.AddConstraint(
            model_name='registeredfood',
            constraint=models.UniqueConstraint(fields=('user_profile', 'food'), name='unique_user_food'),
        ),
        migrations.AddField(
            model_name='foodconsumed',
            name='registered_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed', to='foods.registeredfood'),
        ),
        migrations.CreateModel(
            name='BreakfastConsumed',
            fields=[
            ],
            options={
                'verbose_name': 'Breakfast',
                'verbose_name_plural': 'Breakfasts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foods.foodconsumed',),
        ),
        migrations.CreateModel(
            name='DessertConsumed',
            fields=[
            ],
            options={
                'verbose_name': 'Dessert',
                'verbose_name_plural': 'Desserts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foods.foodconsumed',),
        ),
        migrations.CreateModel(
            name='DinnerConsumed',
            fields=[
            ],
            options={
                'verbose_name': 'Dinner',
                'verbose_name_plural': 'Dinners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foods.foodconsumed',),
        ),
        migrations.CreateModel(
            name='LunchConsumed',
            fields=[
            ],
            options={
                'verbose_name': 'Lunch',
                'verbose_name_plural': 'Lunches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foods.foodconsumed',),
        ),
        migrations.CreateModel(
            name='SnacksConsumed',
            fields=[
            ],
            options={
                'verbose_name': 'Snack registered',
                'verbose_name_plural': 'Snacks registered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foods.foodconsumed',),
        ),
    ]
