# Generated by Django 3.2.12 on 2022-04-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20220420_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodconsumed',
            options={'ordering': ['-created'], 'verbose_name': 'Food Consumed', 'verbose_name_plural': 'Foods Consumed'},
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.IntegerField(default=100, help_text='g/ml'),
        ),
        migrations.AlterField(
            model_name='foodconsumed',
            name='grams',
            field=models.IntegerField(),
        ),
    ]
