django_app:
  build: ./
  ports:
    - 8000:8000
  links:
    - db:localhost

db:
  image: postgres
  environment:
    POSTGRES_USER: testing_user
    POSTGRES_PASSWORD: testing
    POSTGRES_DB: calorie_counter_development
